### ISSUE TITLE
critical: bug in stepsize for non-MKS models

### ISSUE THREAD

**Issue by gnwong** [AFD-Illinois/ipole#55]
Christian Fromm identified a bug in the way the i-suite calculates stepsize: ```stepsize``` assumes X2 is bounded above by 1. See the relevant ipole line of code here:

https://github.com/AFD-Illinois/ipole/blob/63b2aa7b216bfe6ec16cbec46de0cce9ccf6986b/src/model_geodesics.c#L57

Perhaps the most correct way to deal with this is to include ```stepsize``` in the model files and (in the iharm model) explicitly load x2_max, since there's nothing in the iharm file format that forces x2_max == 1.

**Comment by bprather** [comment]
This is fixed in dev: https://github.com/AFD-Illinois/ipole/blob/dev/src/model_geodesics.c#L208

**Comment by gnwong** [comment]
The circle closes!
